BEM exercise
clever-cr/bemexercise pull request #1
Opened 2022-09-30 17:04 UTC by clever-cr

2022-10-03 06:24 UTC, sezeranoJchrisostome requested changes
Well done, I left some comments for you check them out

2022-10-03 06:24 UTC, sezeranoJchrisostome commented on index.html
> +        <div class="content2_line"></div>
this should be an element `content2_line`

2022-10-03 06:24 UTC, sezeranoJchrisostome commented on index.html
> +<div class="teamsection__card">
You can use `ctrl + alt + f` to format you document in perfect view

2022-10-04 07:18 UTC, sezeranoJchrisostome approved these changes
LGTM

2022-10-04 09:01 UTC, rithaven approved these changes

2022-10-06 11:49 UTC, Morrism1 approved these changes
Good Job! 🚀🚀

2022-10-06 11:49 UTC, Morrism1 commented on index.html
> +        <div>
DIV elements with no class. These are unnecessary. If you still need it for some reasons give it a class.

2026-06-13 13:00 UTC, closed without merging